using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Timers;
using TrafficLights.BLL;

namespace TrafficLights
{
	class Program
	{
		static void Main(string[] args)
		{
			//THIS PROGRAM IS DESIGNED TO SIMULATE A TRAFFIC INTERSECTION.
			//IT RANDOMLY GENERATES CARS AND PEDESTRIANS TO APPROACH THE INTERSECTION
			//FROM DIFFERENT DIRECTIONS WHERE THEY WILL ACTIVATE A PRESSURE PLATE
			//OR A PEDESTRIAN BUTTON, WHICH IS USED TO CHANGE THE LIGHTS AT A
			//USER SPECIFIED INTERVAL. MY NEXT PLAN IS TO IMPLEMENT LEFT TURN
			//LANES AND ARROWS TO INCREASE THE COMPLEXITY OF THE LIGHT INTERACTIONS.

			menu.Start();
		}
	}
}
